export const ERRORS ={
    NOT_FOUND: 'Page not found',
    UNAUTHORIZED: 'Unauthorized',
    FORBIDDEN: 'Forbidden',
    SERVER_ERROR: 'Server error',
    GENERIC_ERROR: 'An error occurred',
    VALIDATION_ERROR: 'Validation error',
    AUTHENTICATION_ERROR: 'Authentication error',
    DECRYPTION_ERROR: 'Decryption error',
    ENCRYPTION_ERROR: 'Encryption error',
    DATABASE_ERROR: 'Database error',
    FILE_UPLOAD_ERROR: 'File upload error',
    FILE_DOWNLOAD_ERROR: 'File download error',
    FILE_PROCESSING_ERROR: 'File processing error',
    CAPTCHA_ERROR: 'Captcha error',
    CAPTCHA_VERIFICATION_ERROR: 'Captcha verification error',
    CAPTCHA_SOLUTION_ERROR: 'Captcha solution error',
    CAPTCHA_SOLUTION_EXPIRED_ERROR: 'Captcha solution expired error',
}